global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Threading.Tasks;
global using System.Text;
global using DeathStarLibrary.Entiteti;
global using NHibernate;
global using static DeathStarLibrary.Extensions;
global using System.Diagnostics.CodeAnalysis;
global using FluentNHibernate.Mapping;
global using DeathStarLibrary.DataProviders;
global using DeathStarLibrary.DTOs;
global using SPBDeathStarProjekatIII;
global using DeathStarLibrary;
global using NHibernate.Linq;