@WebAPI_HostAddress = https://localhost:7234
@idBorbeniBrod = 171

GET {{WebAPI_HostAddress}}/BorbeniBrod/ReturnAllBorbeniBrod

###

GET {{WebAPI_HostAddress}}/BorbeniBrod/ReturnBorbeniBrodById/{{idBorbeniBrod}}

###

POST {{WebAPI_HostAddress}}/BorbeniBrod/AddBorbeniBrod
Content-Type: application/json

{
    "brojTopova": 1,
    "posedujeFotTorp": "N",
    "tip": "Krstarica",
    "naziv": "Brodic2",
    "maxBrzina": 0,
    "Savez": {
        "SavezId":101
    },
    "Planeta": {
        "PlanetaId":1
    }
}

###

PATCH {{WebAPI_HostAddress}}/BorbeniBrod/UpdateBorbeniBrod
Content-Type: application/json

{
   "brodID": 163,
   "brojTopova": 1,
   "posedujeFotTorp": "Y",
   "tip": "Krstarica",
   "naziv": "Brodiccc",
   "maxBrzina": 0
}

###

DELETE {{WebAPI_HostAddress}}/BorbeniBrod/DeleteBorbeniBrod/{{idBorbeniBrod}}

###

