
@WebAPI_HostAddress = https://localhost:7234
@idBrod = 161

GET {{WebAPI_HostAddress}}/Brod/ReturnAllBrod

###

GET {{WebAPI_HostAddress}}/Brod/ReturnBrodById/{{idBrod}}

###

POST {{WebAPI_HostAddress}}/Brod/AddBrod
Content-Type: application/json

{
   "naziv": "Galactica",
   "maxBrzina": 0,
   "savez": {
     "savezID": 101
   },
   "planeta": {
     "planetaID": 1
   }
}

###

PATCH {{WebAPI_HostAddress}}/Brod/UpdateBrod
Content-Type: application/json

{
   "brodID": 161,
   "naziv": "Brodic",
   "maxBrzina": 0
}

###
DELETE {{WebAPI_HostAddress}}/Brod/DeleteBrod/{{idBrod}}

###

