@WebAPI_HostAddress = https://localhost:7234
@idGrad = 1

GET {{WebAPI_HostAddress}}/Grad/ReturnAllGrad

###

GET {{WebAPI_HostAddress}}/Grad/ReturnGradById/{{idGrad}}

###

POST {{WebAPI_HostAddress}}/Grad/AddGrad
Content-Type: application/json

{
    "naziv": "Metropolis"
}

###

PATCH {{WebAPI_HostAddress}}/Grad/UpdateGrad
Content-Type: application/json

{
   "gradID": 1,
   "naziv:" "Nis"
}

###
DELETE {{WebAPI_HostAddress}}/Grad/DeleteGrad/{{idGrad}}

###


