@WebAPI_HostAddress = https://localhost:7234
@idIgrac = 1143

GET {{WebAPI_HostAddress}}/Igrac/ReturnAllIgrac

###

POST {{WebAPI_HostAddress}}/Igrac/AddIgrac
Content-Type: application/json

{
    "IgracID":"0",
    "naziv": "Prophet Alliance",
    "datumformiranja": "2024-05-19T23:06:35"
}

###

PATCH {{WebAPI_HostAddress}}/Igrac/UpdateIgrac
Content-Type: application/json

{
   "IgracID": 1143,
   "naziv": "Prophet Alliance",
   "datumFormiranja": "2024-05-19T23:06:35"

}

###
GET {{WebAPI_HostAddress}}/Igrac/ReturnIgracById/{{idIgrac}}

###
//1143
DELETE {{WebAPI_HostAddress}}/Igrac/DeleteIgrac/{{idIgrac}}

###
