@WebAPI_HostAddress = https://localhost:7234
@idIgrac = 181

GET {{WebAPI_HostAddress}}/Igrac/ReturnAllIgrac

###

GET {{WebAPI_HostAddress}}/Igrac/ReturnIgracById/{{idIgrac}}

###

POST {{WebAPI_HostAddress}}/Igrac/AddIgrac
Content-Type: application/json

{
    "korisnickoIme": "QueenFrontman",
    "datumOtvaranjaNaloga": "1970-09-05T23:06:35",
    "lIme": "Freddie",
    "prezime": "Mercury",
    "sSlovo": "M",
    "email": "freddiemercury@example.com",
    "pol": "M",
    "datumRodjenja": "2024-05-19T23:05:11",
    "drzava": "Zanzibar",
    "opis": "Seven seas of rhye",
    "slika": "googledrive.freddie.profilnaslika"
}

###

PATCH {{WebAPI_HostAddress}}/Igrac/UpdateIgrac
Content-Type: application/json

{
    "IgracID": 181,
    "korisnickoIme": "QueenFrontman",
    "datumOtvaranjaNaloga": "1970-09-05T23:06:35",
    "lIme": "Freddie",
    "prezime": "Mercury",
    "sSlovo": "M",
    "email": "freddiemercury@example.com",
    "pol": "M",
    "datumRodjenja": "1946-09-05T23:05:11",
    "drzava": "Zanzibar",
    "opis": "Seven seas of rhye",
    "slika": "googledrive.freddie.profilnaslika"

}
###
//1143
DELETE {{WebAPI_HostAddress}}/Igrac/DeleteIgrac/{{idIgrac}}

###
