@WebAPI_HostAddress = https://localhost:7234
@idKvadrant = 143

GET {{WebAPI_HostAddress}}/Kvadrant/ReturnAllKvadrant


###

GET {{WebAPI_HostAddress}}/Kvadrant/ReturnKvadrantById/{{idKvadrant}}

###

POST {{WebAPI_HostAddress}}/Kvadrant/AddKvadrant
Content-Type: application/json

{
    "redniBroj": 6,
    "procenjenPrecnik": 2344234,
    "galaksija": {
      "galaksijaID": 1
    }
}

###

PATCH {{WebAPI_HostAddress}}/Kvadrant/UpdateKvadrant
Content-Type: application/json

{
   "kvadrantID" : 143,
   "redniBroj": 1,
   "procenjenPrecnik": 111111
}


###
DELETE {{WebAPI_HostAddress}}/Kvadrant/DeleteKvadrant/{{idKvadrant}}

###


