@WebAPI_HostAddress = https://localhost:7234
@idPlaneta = 1063

GET {{WebAPI_HostAddress}}/Planeta/ReturnAllPlaneta
###

GET {{WebAPI_HostAddress}}/Planeta/ReturnPlanetaById/{{idPlaneta}}

###

POST {{WebAPI_HostAddress}}/Planeta/AddPlaneta
Content-Type: application/json

{
      "naziv": "Trapist1B",
      "x": 234234234,
      "y": -235235235,
      "z": 252352523,
      "brojStanovnika": 0,
      "drustvenoUredjenje": "nema",
      "plutonijumKol": 1,
      "berilijumKol": 2,
      "trilijumKol": 3,
      "jeMaticna": "N",
      "glavniGrad": {
          "GradId":1
      },
      "galaksija": {
        "galaksijaID": 1
      },
      "vlasnik": {
        "igracID": 1
      },
      "dominantnaRasa": {
        "rasaID": 1
      }
}

###

PATCH {{WebAPI_HostAddress}}/Planeta/UpdatePlaneta
Content-Type: application/json

{
    "PlanetaID":1063,
    "naziv": "Trapist1B",
      "x": 234234234,
      "y": -235235235,
      "z": 252352523,
      "brojStanovnika": 1,
      "drustvenoUredjenje": "Samoca",
      "plutonijumKol": 1,
      "berilijumKol": 2,
      "trilijumKol": 3,
      "jeMaticna": "N",
      "glavniGrad": {
          "GradId":1
      },
      "galaksija": {
        "galaksijaID": 1
      },
      "vlasnik": {
        "igracID": 1
      },
      "dominantnaRasa": {
        "rasaID": 1
      }

}

###
//1143
DELETE {{WebAPI_HostAddress}}/Planeta/DeletePlaneta/{{idPlaneta}}

###
