@WebAPI_HostAddress = https://localhost:7234
@idSirenjePoseda = 123

GET {{WebAPI_HostAddress}}/SirenjePoseda/ReturnAllSirenjePoseda

###

POST {{WebAPI_HostAddress}}/SirenjePoseda/AddSirenjePoseda
Content-Type: application/json

{
    "tip": "Prostorija",
    "datum": "2024-04-15T00:00:00",
    "savez":{
      "savezID": 101
    },
    "prethodniVlasnik": {
      "igracID": 1
    }
}

###

PATCH {{WebAPI_HostAddress}}/SirenjePoseda/UpdateSirenjePoseda
Content-Type: application/json

{
   "spid": 123,
   "tip": "Nesto",
   "datum": "2023-04-15T00:00:00"
}

###
GET {{WebAPI_HostAddress}}/SirenjePoseda/ReturnSirenjePosedaById/{{idSirenjePoseda}}

###
DELETE {{WebAPI_HostAddress}}/SirenjePoseda/DeleteSirenjePoseda/{{idSirenjePoseda}}

###

