@WebAPI_HostAddress = https://localhost:7234
@idSpisakOruzja = 100

GET {{WebAPI_HostAddress}}/SpisakOruzja/ReturnAllSpisakOruzja

###

POST {{WebAPI_HostAddress}}/SpisakOruzja/AddSpisakOruzja
Content-Type: application/json

{
    "oruzje": "Foton Torpedo",
    "svemirskaStanica": {
      "ssid": 1
    }
}

###

PATCH {{WebAPI_HostAddress}}/SpisakOruzja/UpdateSpisakOruzja
Content-Type: application/json

{
   "soid": 100,
   "oruzje": "Kul oruzje"
}

###
GET {{WebAPI_HostAddress}}/SpisakOruzja/ReturnSpisakOruzjaById/{{idSpisakOruzja}}

###
DELETE {{WebAPI_HostAddress}}/SpisakOruzja/DeleteSpisakOruzja/{{idSpisakOruzja}}

###


