@WebAPI_HostAddress = https://localhost:7234
@idSvemirskaStanica = 136

GET {{WebAPI_HostAddress}}/SvemirskaStanica/ReturnAllSvemirskaStanica

###

POST {{WebAPI_HostAddress}}/SvemirskaStanica/AddSvemirskaStanica
Content-Type: application/json

{
    "naziv": "Orbita 7",
    "brojLjudi": 100,
    "velicina": 2500,
    "rastojanjeOP": 300000,
    "tip": "Vojna",
    "namena": "Trgovina",
    "planeta": {
        "planetaID": 1
    }
}

###

PATCH {{WebAPI_HostAddress}}/SvemirskaStanica/UpdateSvemirskaStanica
Content-Type: application/json

{
   "ssid": 136,
   "naziv": "Neka druga",
   "brojLjudi": 100,
   "velicina": 2500,
   "rastojanjeOP": 300000,
   "tip": "Vojna",
   "namena": "Trgovina"
}

###
GET {{WebAPI_HostAddress}}/SvemirskaStanica/ReturnSvemirskaStanicaById/{{idSvemirskaStanica}}

###
DELETE {{WebAPI_HostAddress}}/SvemirskaStanica/DeleteSvemirskaStanica/{{idSvemirskaStanica}}

###


