@WebAPI_HostAddress = https://localhost:7234
@idTransportniBrod = 176

GET {{WebAPI_HostAddress}}/TransportniBrod/ReturnAllTransportniBrod

###

GET {{WebAPI_HostAddress}}/TransportniBrod/ReturnTransportniBrodById/{{idTransportniBrod}}


###
POST {{WebAPI_HostAddress}}/TransportniBrod/AddTransportniBrod
Content-Type: application/json

{
    "nosivost": 15460,
    "zastita": "N",
    "naziv": "Galkticus expess",
    "maxBrzina": 1000,
    "Savez": {
        "SavezId":101
    },
    "Planeta": {
        "PlanetaId":1
    }

}

###

PATCH {{WebAPI_HostAddress}}/TransportniBrod/UpdateTransportniBrod
Content-Type: application/json

{
    "nosivost": 15460,
    "zastita": "N",
    "naziv": "Brodus Maximus",
    "maxBrzina": 1000,
    "Savez": {
        "SavezId":101
    },
    "Planeta": {
        "PlanetaId":1
    }
}
###
DELETE {{WebAPI_HostAddress}}/TransportniBrod/DeleteTransportniBrod/{{idTransportniBrod}}

###



