@WebAPI_HostAddress = https://localhost:7234
@idTransportniBrod = 182

GET {{WebAPI_HostAddress}}/TransportniBrod/ReturnAllTransportniBrod

###

POST {{WebAPI_HostAddress}}/TransportniBrod/AddTransportniBrod
Content-Type: application/json

{
    "nosivost": 10000,
    "zastita": "n",
    "naziv": null,
    "maxBrzina": 0
}

###

PATCH {{WebAPI_HostAddress}}/TransportniBrod/UpdateTransportniBrod
Content-Type: application/json

{
   "brodID" : 102,
   "nosivost": 10000,
    "zastita": "y",
    "naziv": null,
    "maxBrzina": 0
}

###
GET {{WebAPI_HostAddress}}/TransportniBrod/ReturnTransportniBrodById/{{idTransportniBrod}}

###
DELETE {{WebAPI_HostAddress}}/TransportniBrod/DeleteTransportniBrod/{{idTransportniBrod}}

###



