@WebAPI_HostAddress = https://localhost:7234
@idZvezda = 141

GET {{WebAPI_HostAddress}}/Zvezda/ReturnAllZvezda

###

POST {{WebAPI_HostAddress}}/Zvezda/AddZvezda
Content-Type: application/json

{
    "naziv": "Prophet Alliance",
    "Tip": "Red supergiant"
}

###

PATCH {{WebAPI_HostAddress}}/Zvezda/UpdateZvezda
Content-Type: application/json

{
   "naziv": "Prophet Alliance",
   "Tip": "Red hypergiant"

}

###
GET {{WebAPI_HostAddress}}/Zvezda/ReturnZvezdaById/{{idZvezda}}

###
//1143
DELETE {{WebAPI_HostAddress}}/Zvezda/DeleteZvezda/{{idZvezda}}

###
